blank_issues_enabled: false

contact_links:
  - name: 使用文档
    url: http://furion.baiqian.ltd/
    about: 让 .NET 开发更简单，更通用，更流行。
  - name: 慷慨赞助
    url: http://furion.baiqian.ltd/docs/donate
    about: 允许商用，慷慨赞助
